//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreAssitant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _string {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _string() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreAssitant.string", typeof(_string).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        internal static string Account_infomation {
            get {
                return ResourceManager.GetString("Account infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm hình ảnh.
        /// </summary>
        internal static string Add_picture {
            get {
                return ResourceManager.GetString("Add picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mặt hàng.
        /// </summary>
        internal static string AddPro {
            get {
                return ResourceManager.GetString("AddPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mã giảm giá.
        /// </summary>
        internal static string AddVoucher {
            get {
                return ResourceManager.GetString("AddVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nâng cao.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng được sử dụng.
        /// </summary>
        internal static string Amount_be_used {
            get {
                return ResourceManager.GetString("Amount be used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn muốn xóa tài khoản này?.
        /// </summary>
        internal static string Areusure {
            get {
                return ResourceManager.GetString("Areusure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string beleo {
            get {
                return ResourceManager.GetString("beleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File quá lớn.
        /// </summary>
        internal static string bigfile {
            get {
                return ResourceManager.GetString("bigfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn phải lớn hơn ngày hiện tại.
        /// </summary>
        internal static string BiggerNow {
            get {
                return ResourceManager.GetString("BiggerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập số lớn hơn 0.
        /// </summary>
        internal static string BiggerZero {
            get {
                return ResourceManager.GetString("BiggerZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa đơn.
        /// </summary>
        internal static string Bill_code {
            get {
                return ResourceManager.GetString("Bill code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác sẽ không thể phục hồi.
        /// </summary>
        internal static string Cannotrehibilitate {
            get {
                return ResourceManager.GetString("Cannotrehibilitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu Ngân.
        /// </summary>
        internal static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thông tin món ăn.
        /// </summary>
        internal static string ChangeProInf {
            get {
                return ResourceManager.GetString("ChangeProInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu đồ.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh.
        /// </summary>
        internal static string Chosse {
            get {
                return ResourceManager.GetString("Chosse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thời gian.
        /// </summary>
        internal static string ChosseTime {
            get {
                return ResourceManager.GetString("ChosseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn đóng ứng dụng?.
        /// </summary>
        internal static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã:.
        /// </summary>
        internal static string Code_ {
            get {
                return ResourceManager.GetString("Code:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã code đã tồn tại.
        /// </summary>
        internal static string CodeIsExists {
            get {
                return ResourceManager.GetString("CodeIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu:.
        /// </summary>
        internal static string Confirm_password_ {
            get {
                return ResourceManager.GetString("Confirm password:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thanh toán.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh:.
        /// </summary>
        internal static string Date_of_birth_ {
            get {
                return ResourceManager.GetString("Date of birth:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phải nhỏ hơn hôm nay.
        /// </summary>
        internal static string DayNotNow {
            get {
                return ResourceManager.GetString("DayNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặc định.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string Define {
            get {
                return ResourceManager.GetString("Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài khoản.
        /// </summary>
        internal static string DelAcc {
            get {
                return ResourceManager.GetString("DelAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả chi tiết:.
        /// </summary>
        internal static string Detailed_description_ {
            get {
                return ResourceManager.GetString("Detailed description:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string Different {
            get {
                return ResourceManager.GetString("Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước cửa sổ.
        /// </summary>
        internal static string Doorsize {
            get {
                return ResourceManager.GetString("Doorsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập giá trị từ 0 đến.
        /// </summary>
        internal static string Enter_From {
            get {
                return ResourceManager.GetString("Enter_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi nhập.
        /// </summary>
        internal static string EnterError {
            get {
                return ResourceManager.GetString("EnterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi định dạng.
        /// </summary>
        internal static string ErorFormat {
            get {
                return ResourceManager.GetString("ErorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu bị lỗi.
        /// </summary>
        internal static string Error_data {
            get {
                return ResourceManager.GetString("Error data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 Not Found.
        /// </summary>
        internal static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu không đúng.
        /// </summary>
        internal static string ErrorAgainPass {
            get {
                return ResourceManager.GetString("ErrorAgainPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được vượt quá 100 triệu.
        /// </summary>
        internal static string ErrorBigger100M {
            get {
                return ResourceManager.GetString("ErrorBigger100M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu hiện tại không đúng.
        /// </summary>
        internal static string ErrorNowPass {
            get {
                return ResourceManager.GetString("ErrorNowPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn sử dụng.
        /// </summary>
        internal static string Expiry_date {
            get {
                return ResourceManager.GetString("Expiry date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài khoản thất bại.
        /// </summary>
        internal static string failDel {
            get {
                return ResourceManager.GetString("failDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string Felmale {
            get {
                return ResourceManager.GetString("Felmale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string Forgot_password_ {
            get {
                return ResourceManager.GetString("Forgot password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày:.
        /// </summary>
        internal static string From_ {
            get {
                return ResourceManager.GetString("From:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày:.
        /// </summary>
        internal static string From_day_ {
            get {
                return ResourceManager.GetString("From day:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ tháng:.
        /// </summary>
        internal static string From_month_ {
            get {
                return ResourceManager.GetString("From month:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập giá trị trong khoảng 0 đến 100.
        /// </summary>
        internal static string From0to100 {
            get {
                return ResourceManager.GetString("From0to100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập giá trị trong khoảng 0 đến 10000.
        /// </summary>
        internal static string From0to10000 {
            get {
                return ResourceManager.GetString("From0to10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string Full_name {
            get {
                return ResourceManager.GetString("Full name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính:.
        /// </summary>
        internal static string Gender_ {
            get {
                return ResourceManager.GetString("Gender:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chung.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền trả lại.
        /// </summary>
        internal static string Give {
            get {
                return ResourceManager.GetString("Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào, .
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí nhân sự.
        /// </summary>
        internal static string Human_Resource_Management {
            get {
                return ResourceManager.GetString("Human Resource Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn tại thông tin chưa hợp lệ.
        /// </summary>
        internal static string illegal {
            get {
                return ResourceManager.GetString("illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string illegalPhonenumber {
            get {
                return ResourceManager.GetString("illegalPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cửa hàng.
        /// </summary>
        internal static string InfoSrore {
            get {
                return ResourceManager.GetString("InfoSrore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bàn.
        /// </summary>
        internal static string List_table {
            get {
                return ResourceManager.GetString("List table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên:.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cửa hàng:.
        /// </summary>
        internal static string Namestore_ {
            get {
                return ResourceManager.GetString("Namestore:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới trùng với mật khẩu hiện tại.
        /// </summary>
        internal static string NewLikeOld {
            get {
                return ResourceManager.GetString("NewLikeOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không để trống.
        /// </summary>
        internal static string NoEmpty {
            get {
                return ResourceManager.GetString("NoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không xác định.
        /// </summary>
        internal static string Nondefine {
            get {
                return ResourceManager.GetString("Nondefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn trống, chưa có đồ ăn.
        /// </summary>
        internal static string NoProductInTable {
            get {
                return ResourceManager.GetString("NoProductInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng không nhập các kí tự đặc biệt.
        /// </summary>
        internal static string NoSpecialChar {
            get {
                return ResourceManager.GetString("NoSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách chưa đưa đủ tiền.
        /// </summary>
        internal static string NotEnougnMOney {
            get {
                return ResourceManager.GetString("NotEnougnMOney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại.
        /// </summary>
        internal static string Old_password {
            get {
                return ResourceManager.GetString("Old password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ nhập chữ cái thường, số và khoảng trắng{0}Phân cách giữa các tag bằng dấu chấm phẩy &apos;;&apos;.
        /// </summary>
        internal static string Onlychar {
            get {
                return ResourceManager.GetString("Onlychar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được phép nhập số.
        /// </summary>
        internal static string OnlyNumber {
            get {
                return ResourceManager.GetString("OnlyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu:.
        /// </summary>
        internal static string Password_ {
            get {
                return ResourceManager.GetString("Password:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HÓA ĐƠN THANH TOÁN.
        /// </summary>
        internal static string PAY_BILL {
            get {
                return ResourceManager.GetString("PAY BILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT:.
        /// </summary>
        internal static string Phone_ {
            get {
                return ResourceManager.GetString("Phone:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chỉ nhập số nguyên dương.
        /// </summary>
        internal static string PlusChar {
            get {
                return ResourceManager.GetString("PlusChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền:.
        /// </summary>
        internal static string Position_ {
            get {
                return ResourceManager.GetString("Position:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán:.
        /// </summary>
        internal static string Price_ {
            get {
                return ResourceManager.GetString("Price:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi thông tin món ăn.
        /// </summary>
        internal static string ProError {
            get {
                return ResourceManager.GetString("ProError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công trình đang thi công!.
        /// </summary>
        internal static string Project_ing {
            get {
                return ResourceManager.GetString("Project_ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string Quantum {
            get {
                return ResourceManager.GetString("Quantum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại lần 2.
        /// </summary>
        internal static string Re_enter_new_password {
            get {
                return ResourceManager.GetString("Re-enter new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn lại.
        /// </summary>
        internal static string Remain {
            get {
                return ResourceManager.GetString("Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập phần mô tả có độ dài ngắn hơn 300 kí tự.
        /// </summary>
        internal static string Require_300_Char {
            get {
                return ResourceManager.GetString("Require_300_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên có độ dài ngắn hơn 50 kí tự.
        /// </summary>
        internal static string Require_50_Char {
            get {
                return ResourceManager.GetString("Require_50_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là thông tin bắt buộc.
        /// </summary>
        internal static string RequireInfo {
            get {
                return ResourceManager.GetString("RequireInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng doanh thu .
        /// </summary>
        internal static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOANH THU.
        /// </summary>
        internal static string revenue_ {
            get {
                return ResourceManager.GetString("revenue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn lưu thay đổi?.
        /// </summary>
        internal static string SaveChange {
            get {
                return ResourceManager.GetString("SaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài Đặt.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí.
        /// </summary>
        internal static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí thành viên mới.
        /// </summary>
        internal static string SignUpName {
            get {
                return ResourceManager.GetString("SignUpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhân viên.
        /// </summary>
        internal static string Staff_infomation {
            get {
                return ResourceManager.GetString("Staff infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống Kê.
        /// </summary>
        internal static string Statistical {
            get {
                return ResourceManager.GetString("Statistical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của hàng.
        /// </summary>
        internal static string StoreInfo {
            get {
                return ResourceManager.GetString("StoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu:.
        /// </summary>
        internal static string Stype_ {
            get {
                return ResourceManager.GetString("Stype:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công!.
        /// </summary>
        internal static string SuccessChangePass {
            get {
                return ResourceManager.GetString("SuccessChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản nhân viên thành công!.
        /// </summary>
        internal static string SuccessCreateAcc {
            get {
                return ResourceManager.GetString("SuccessCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài khoản thành công.
        /// </summary>
        internal static string SuccessDel {
            get {
                return ResourceManager.GetString("SuccessDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn:.
        /// </summary>
        internal static string Table_ {
            get {
                return ResourceManager.GetString("Table:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền khách đưa.
        /// </summary>
        internal static string Take {
            get {
                return ResourceManager.GetString("Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mang về.
        /// </summary>
        internal static string Take_home {
            get {
                return ResourceManager.GetString("Take home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian:.
        /// </summary>
        internal static string Time_ {
            get {
                return ResourceManager.GetString("Time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày:.
        /// </summary>
        internal static string To_ {
            get {
                return ResourceManager.GetString("To:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày:.
        /// </summary>
        internal static string To_day_ {
            get {
                return ResourceManager.GetString("To day:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string To_month_ {
            get {
                return ResourceManager.GetString("To month:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị xem:.
        /// </summary>
        internal static string Unit_ {
            get {
                return ResourceManager.GetString("Unit:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        internal static string Unit_price {
            get {
                return ResourceManager.GetString("Unit price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập:.
        /// </summary>
        internal static string User_name_ {
            get {
                return ResourceManager.GetString("User name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị(%).
        /// </summary>
        internal static string Value___ {
            get {
                return ResourceManager.GetString("Value(%)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giảm giá.
        /// </summary>
        internal static string Voucher {
            get {
                return ResourceManager.GetString("Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giảm giá.
        /// </summary>
        internal static string Voucher_code {
            get {
                return ResourceManager.GetString("Voucher code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher.
        /// </summary>
        internal static string Vourcher {
            get {
                return ResourceManager.GetString("Vourcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ảnh có kích thước &lt; 26kb.
        /// </summary>
        internal static string Wanrning {
            get {
                return ResourceManager.GetString("Wanrning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string Website_ {
            get {
                return ResourceManager.GetString("Website:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần.
        /// </summary>
        internal static string week {
            get {
                return ResourceManager.GetString("week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÃ GIẢM GIÁ CỦA BẠN.
        /// </summary>
        internal static string YOUR_VOUCHER {
            get {
                return ResourceManager.GetString("YOUR VOUCHER", resourceCulture);
            }
        }
    }
}
